"""Verified Python code generation."""

from __future__ import annotations

import json

from open_mapping.codegen.common import GeneratedArtifact
from open_mapping.model.mappings import MappingDocument
from open_mapping.model.schema import SchemaDocument
from open_mapping.serialization.mappings import mapping_sha256
from open_mapping.verification.static import require_static_valid

_RUNTIME = r'''
"""Generated by Open Mapping Compiler. Mapping content is data, not executable code."""

from __future__ import annotations

import json
import math
import re
from datetime import datetime, timezone

MAPPING_ID = __MAPPING_ID_REPR__
MAPPING_SHA256 = __MAPPING_SHA_REPR__
MAX_SAFE_INTEGER = 9007199254740991
MAX_EXPRESSION_DEPTH = __MAX_DEPTH__
MAX_ARRAY_ITEMS = __MAX_ARRAY_ITEMS__
MAX_OUTPUT_NODES = __MAX_OUTPUT_NODES__
MAX_STRING_LENGTH = __MAX_STRING_LENGTH__

_MISSING = object()
_RULES = json.loads(__RULES_JSON__)
_TARGETS = tuple(sorted(_RULES, key=lambda path: tuple(token for token in path.strip("/").split("/") if token)))
_DECIMAL = re.compile(r"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$")
_INTEGER = re.compile(r"^[+-]?\d+$")
_RFC3339 = re.compile(r"^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?(Z|[+-]\d{2}:\d{2})$")
_DATE_TOKENS = ("YYYY", "SSS", "MM", "DD", "hh", "mm", "ss", "Z")


def _get(document: object, pointer: str) -> object:
    if pointer == "":
        return document
    current = document
    for token in pointer[1:].split("/"):
        token = token.replace("~1", "/").replace("~0", "~")
        if isinstance(current, dict):
            if token not in current:
                raise RuntimeError("SOURCE_PATH_NOT_FOUND: " + pointer)
            current = current[token]
        elif isinstance(current, list):
            if not token.isdigit() or int(token) >= len(current):
                raise RuntimeError("SOURCE_PATH_NOT_FOUND: " + pointer)
            current = current[int(token)]
        else:
            raise RuntimeError("SOURCE_PATH_NOT_FOUND: " + pointer)
    return current


def _canonical(value: object) -> str:
    if isinstance(value, dict):
        return json.dumps(
            {str(key): json.loads(_canonical(item)) for key, item in sorted(value.items())},
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        )
    if isinstance(value, list):
        return json.dumps([json.loads(_canonical(item)) for item in value], ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        raise ValueError("non-finite number")
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _semantic_equal(left: object, right: object) -> bool:
    if isinstance(left, bool) or isinstance(right, bool):
        return isinstance(left, bool) and isinstance(right, bool) and left == right
    if isinstance(left, (int, float)) or isinstance(right, (int, float)):
        if not isinstance(left, (int, float)) or not isinstance(right, (int, float)):
            return False
        return _semantic_number(left) == _semantic_number(right)
    if isinstance(left, dict) or isinstance(right, dict):
        return isinstance(left, dict) and isinstance(right, dict) and set(left) == set(right) and all(_semantic_equal(left[key], right[key]) for key in left)
    if isinstance(left, list) or isinstance(right, list):
        return isinstance(left, list) and isinstance(right, list) and len(left) == len(right) and all(_semantic_equal(a, b) for a, b in zip(left, right))
    return left == right


def _semantic_number(value: int | float) -> float:
    if isinstance(value, int) and abs(value) > MAX_SAFE_INTEGER:
        raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
    try:
        result = float(value)
    except OverflowError as exc:
        raise RuntimeError("NUMERIC_PRECISION_RISK: number exceeds binary64 range") from exc
    if not math.isfinite(result):
        raise RuntimeError("NUMERIC_PRECISION_RISK: non-finite number")
    if result.is_integer() and abs(result) > MAX_SAFE_INTEGER:
        raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
    return result


def _count_nodes(value: object) -> int:
    if isinstance(value, dict):
        return 1 + sum(_count_nodes(item) for item in value.values())
    if isinstance(value, list):
        return 1 + sum(_count_nodes(item) for item in value)
    return 1


def _check_limits(value: object) -> None:
    if _count_nodes(value) > MAX_OUTPUT_NODES:
        raise RuntimeError("EVALUATION_LIMIT_EXCEEDED: max_output_nodes")
    total = 0

    def visit(item: object) -> None:
        nonlocal total
        if isinstance(item, str):
            total += len(item)
            if total > MAX_STRING_LENGTH:
                raise RuntimeError("EVALUATION_LIMIT_EXCEEDED: max_string_length")
        elif isinstance(item, dict):
            for child in item.values():
                visit(child)
        elif isinstance(item, list):
            for child in item:
                visit(child)

    visit(value)


def _numeric(value: object) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise RuntimeError("TYPE_MISMATCH: numeric operation requires a number")
    if isinstance(value, int) and abs(value) > MAX_SAFE_INTEGER:
        raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
    try:
        result = float(value)
    except OverflowError as exc:
        raise RuntimeError("NUMERIC_PRECISION_RISK: number exceeds binary64 range") from exc
    if not math.isfinite(result):
        raise RuntimeError("NUMERIC_PRECISION_RISK: non-finite number")
    return result


def _normalize_number(value: float) -> int | float:
    if not math.isfinite(value):
        raise RuntimeError("NUMERIC_PRECISION_RISK: non-finite result")
    if value.is_integer() and abs(value) <= MAX_SAFE_INTEGER:
        return int(value)
    if abs(value) > MAX_SAFE_INTEGER:
        raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer result")
    return value


def _round_half(value: float, digits: int) -> int | float:
    factor = 10 ** digits
    scaled = math.floor(abs(value) * factor + 0.5) / factor
    return _normalize_number(math.copysign(scaled, value) if value != 0 else 0.0)


def _cast(value: object, target_type: str) -> object:
    if target_type == "string":
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, float) and value.is_integer():
            return str(int(value))
        if isinstance(value, (str, int, float)):
            return str(value)
        raise RuntimeError("TYPE_MISMATCH: cast to string requires scalar")
    if target_type == "boolean":
        if isinstance(value, bool):
            return value
        if isinstance(value, str) and value.lower() in {"true", "false"}:
            return value.lower() == "true"
        raise RuntimeError("TYPE_MISMATCH: cast to boolean requires boolean")
    if target_type == "integer":
        if isinstance(value, bool):
            raise RuntimeError("TYPE_MISMATCH: cast to integer rejects booleans")
        if isinstance(value, int):
            if abs(value) > MAX_SAFE_INTEGER:
                raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
            return value
        if isinstance(value, str) and _INTEGER.fullmatch(value):
            parsed = int(value, 10)
            if abs(parsed) > MAX_SAFE_INTEGER:
                raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
            return parsed
        raise RuntimeError("TYPE_MISMATCH: cast to integer requires integer string")
    if target_type == "number":
        if isinstance(value, bool):
            raise RuntimeError("TYPE_MISMATCH: cast to number rejects booleans")
        if isinstance(value, str):
            if not _DECIMAL.fullmatch(value):
                raise RuntimeError("TYPE_MISMATCH: cast to number requires finite numeric value")
            parsed = float(value)
        elif isinstance(value, (int, float)):
            if isinstance(value, int) and abs(value) > MAX_SAFE_INTEGER:
                raise RuntimeError("NUMERIC_PRECISION_RISK: unsafe integer")
            parsed = float(value)
        else:
            raise RuntimeError("TYPE_MISMATCH: cast to number requires finite numeric value")
        if not math.isfinite(parsed):
            raise RuntimeError("TYPE_MISMATCH: cast to number requires finite numeric value")
        return _normalize_number(parsed)
    raise RuntimeError("INVALID_EXPRESSION: unknown cast target")


def _parse_date(value: object) -> str:
    if not isinstance(value, str):
        raise RuntimeError("INVALID_DATE: parse_date requires string")
    match = _RFC3339.fullmatch(value)
    if match is None:
        raise RuntimeError("INVALID_DATE: invalid RFC3339")
    year, month, day, hour, minute, second = (int(match.group(index)) for index in range(1, 7))
    if hour > 23 or minute > 59 or second > 59:
        raise RuntimeError("INVALID_DATE: invalid RFC3339 component")
    fraction = match.group(7) or ""
    try:
        parsed = datetime(year, month, day, hour, minute, second, int(fraction[:6].ljust(6, "0")), tzinfo=timezone.utc)
    except ValueError as exc:
        raise RuntimeError("INVALID_DATE: invalid RFC3339 calendar date") from exc
    zone = match.group(8)
    if zone != "Z":
        offset_hours = int(zone[1:3])
        offset_minutes = int(zone[4:6])
        if offset_hours > 23 or offset_minutes > 59:
            raise RuntimeError("INVALID_DATE: invalid RFC3339 offset")
        offset_seconds = (offset_hours * 60 + offset_minutes) * 60
        try:
            parsed = datetime.fromtimestamp(parsed.timestamp() + (-offset_seconds if zone[0] == "+" else offset_seconds), timezone.utc)
        except (OverflowError, OSError, ValueError) as exc:
            raise RuntimeError("INVALID_DATE: RFC3339 normalization out of range") from exc
    return parsed.strftime("%Y-%m-%dT%H:%M:%S.") + f"{parsed.microsecond // 1000:03d}Z"


def _format_date(value: object, pattern: str) -> str:
    if not isinstance(value, str):
        raise RuntimeError("INVALID_DATE: format_date requires string")
    parsed = _parse_date(value)
    values = {"YYYY": parsed[0:4], "MM": parsed[5:7], "DD": parsed[8:10], "hh": parsed[11:13], "mm": parsed[14:16], "ss": parsed[17:19], "SSS": parsed[20:23], "Z": "Z"}
    output: list[str] = []
    index = 0
    while index < len(pattern):
        for token in _DATE_TOKENS:
            if pattern.startswith(token, index):
                output.append(values[token])
                index += len(token)
                break
        else:
            if pattern[index] != "T" and pattern[index].isascii() and pattern[index].isalpha():
                raise RuntimeError("INVALID_DATE: unsupported date format token")
            output.append(pattern[index])
            index += 1
    return "".join(output)


def _evaluate(expression: dict[str, object], input_document: object, output_document: object, current_stack: list[object], depth: int) -> object:
    if depth > MAX_EXPRESSION_DEPTH:
        raise RuntimeError("EVALUATION_LIMIT_EXCEEDED: max_expression_depth")
    op = expression["op"]
    if op == "get":
        document = expression.get("document", "input")
        path = str(expression["path"])
        if document == "input":
            return _get(input_document, path)
        if document == "output":
            return _get(output_document, path)
        if not current_stack:
            raise RuntimeError("INVALID_EXPRESSION: current requires map context")
        return _get(current_stack[-1], path)
    if op == "literal":
        return expression["value"]
    if op == "object":
        return {key: _evaluate(child, input_document, output_document, current_stack, depth + 1) for key, child in dict(expression["fields"]).items()}
    if op == "array":
        items = list(expression["items"])
        if len(items) > MAX_ARRAY_ITEMS:
            raise RuntimeError("EVALUATION_LIMIT_EXCEEDED: max_array_items")
        return [_evaluate(item, input_document, output_document, current_stack, depth + 1) for item in items]
    if op == "map":
        collection = _evaluate(expression["collection"], input_document, output_document, current_stack, depth + 1)
        if not isinstance(collection, list):
            raise RuntimeError("TYPE_MISMATCH: map requires array")
        if len(collection) > MAX_ARRAY_ITEMS:
            raise RuntimeError("EVALUATION_LIMIT_EXCEEDED: max_array_items")
        return [
            _evaluate(
                expression["expression"],
                input_document,
                output_document,
                current_stack + [item],
                depth + 1,
            )
            for item in collection
        ]
    if op == "coalesce":
        for operand in list(expression["operands"]):
            try:
                value = _evaluate(operand, input_document, output_document, current_stack, depth + 1)
            except RuntimeError as exc:
                if str(exc).startswith("SOURCE_PATH_NOT_FOUND"):
                    continue
                raise
            if value is not _MISSING and value is not None:
                return value
        return None
    if op == "concat":
        parts: list[str] = []
        for operand in list(expression["operands"]):
            value = _evaluate(operand, input_document, output_document, current_stack, depth + 1)
            if not isinstance(value, str):
                raise RuntimeError("TYPE_MISMATCH: concat requires strings")
            parts.append(value)
        return str(expression.get("separator", "")).join(parts)
    if op == "cast":
        return _cast(_evaluate(expression["value"], input_document, output_document, current_stack, depth + 1), str(expression["target_type"]))
    if op == "if":
        condition = _evaluate(expression["condition"], input_document, output_document, current_stack, depth + 1)
        if not isinstance(condition, bool):
            raise RuntimeError("TYPE_MISMATCH: if requires boolean")
        branch = expression["then"] if condition else expression["otherwise"]
        return _evaluate(branch, input_document, output_document, current_stack, depth + 1)
    if op == "equals":
        left = _evaluate(expression["left"], input_document, output_document, current_stack, depth + 1)
        right = _evaluate(expression["right"], input_document, output_document, current_stack, depth + 1)
        return _semantic_equal(left, right)
    if op == "not":
        value = _evaluate(expression["value"], input_document, output_document, current_stack, depth + 1)
        if not isinstance(value, bool):
            raise RuntimeError("TYPE_MISMATCH: not requires boolean")
        return not value
    if op in {"and", "or"}:
        values = [_evaluate(item, input_document, output_document, current_stack, depth + 1) for item in list(expression["operands"])]
        if any(not isinstance(item, bool) for item in values):
            raise RuntimeError("TYPE_MISMATCH: boolean operation requires booleans")
        return all(values) if op == "and" else any(values)
    if op == "lookup":
        key = _evaluate(expression["key"], input_document, output_document, current_stack, depth + 1)
        values = dict(expression["values"])
        if isinstance(key, str) and key in values:
            return values[key]
        default = expression.get("default")
        return _evaluate(default, input_document, output_document, current_stack, depth + 1) if default is not None else None
    if op in {"add", "subtract", "multiply", "divide"}:
        left = _numeric(_evaluate(expression["left"], input_document, output_document, current_stack, depth + 1))
        right = _numeric(_evaluate(expression["right"], input_document, output_document, current_stack, depth + 1))
        if op == "add":
            result = left + right
        elif op == "subtract":
            result = left - right
        elif op == "multiply":
            result = left * right
        else:
            if right == 0.0:
                raise RuntimeError("DIVIDE_BY_ZERO")
            result = left / right
        return _normalize_number(result)
    if op == "round":
        value = _numeric(_evaluate(expression["value"], input_document, output_document, current_stack, depth + 1))
        return _round_half(value, int(expression.get("digits", 0)))
    if op == "parse_date":
        return _parse_date(_evaluate(expression["value"], input_document, output_document, current_stack, depth + 1))
    if op == "format_date":
        return _format_date(_evaluate(expression["value"], input_document, output_document, current_stack, depth + 1), str(expression["pattern"]))
    raise RuntimeError("INVALID_EXPRESSION: unknown operation")


def _assign(document: dict[str, object], pointer: str, value: object) -> dict[str, object]:
    tokens = pointer.strip("/").split("/") if pointer else []
    result = dict(document)
    current = result
    for index, token in enumerate(tokens):
        token = token.replace("~1", "/").replace("~0", "~")
        if token.isdigit():
            raise RuntimeError("INVALID_INPUT: numeric target index")
        if index == len(tokens) - 1:
            current[token] = value
        else:
            existing = current.get(token)
            if existing is None or isinstance(existing, dict):
                child = {} if existing is None else dict(existing)
                current[token] = child
                current = child
            else:
                raise RuntimeError("OVERLAPPING_TARGET_ASSIGNMENT")
    return result


def transform(source: dict[str, object]) -> dict[str, object]:
    if not isinstance(source, dict):
        raise RuntimeError("INVALID_INPUT: source must be an object")
    output: dict[str, object] = {}
    for target in _TARGETS:
        rule = _RULES[target]
        value = _evaluate(rule, source, output, [], 0)
        _check_limits(value)
        output = _assign(output, target, value)
    return output
'''


def generate_python(
    mapping: MappingDocument,
    *,
    source_schema: SchemaDocument,
    target_schema: SchemaDocument,
) -> GeneratedArtifact:
    require_static_valid(mapping, source_schema=source_schema, target_schema=target_schema)
    rules = {rule.target: rule.expression.model_dump(mode="json") for rule in mapping.rules}
    source = (
        _RUNTIME.replace("__MAPPING_ID_REPR__", repr(mapping.id))
        .replace("__MAPPING_SHA_REPR__", repr(mapping_sha256(mapping)))
        .replace("__MAX_DEPTH__", "64")
        .replace("__MAX_ARRAY_ITEMS__", "10000")
        .replace("__MAX_OUTPUT_NODES__", "100000")
        .replace("__MAX_STRING_LENGTH__", "1000000")
        .replace("__RULES_JSON__", repr(json.dumps(rules, ensure_ascii=False, sort_keys=True)))
    )
    return GeneratedArtifact(
        language="python",
        mapping_id=mapping.id,
        mapping_sha256=mapping_sha256(mapping),
        source=source,
    )
