"""Verified TypeScript code generation."""

from __future__ import annotations

import json

from open_mapping.codegen.common import GeneratedArtifact
from open_mapping.model.mappings import MappingDocument
from open_mapping.model.schema import SchemaDocument
from open_mapping.serialization.mappings import mapping_sha256
from open_mapping.verification.static import require_static_valid

_RUNTIME = r"""
// Generated by Open Mapping Compiler. Mapping content is data, not executable code.
export const MAPPING_ID = __MAPPING_ID__;
export const MAPPING_SHA256 = __MAPPING_SHA__;
const MAX_SAFE_INTEGER = 9007199254740991;
const MAX_EXPRESSION_DEPTH = 64;
const MAX_ARRAY_ITEMS = 10000;
const MAX_OUTPUT_NODES = 100000;
const MAX_STRING_LENGTH = 1000000;
const RULES: Record<string, Record<string, unknown>> = __RULES__;
const DECIMAL = /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/;
const INTEGER = /^[+-]?\d+$/;
const DATE_TOKENS = ["YYYY", "SSS", "MM", "DD", "hh", "mm", "ss", "Z"] as const;

const TARGETS = Object.keys(RULES).sort((a, b) => {
  const at = a.replace(/^\//, "").split("/");
  const bt = b.replace(/^\//, "").split("/");
  const n = Math.max(at.length, bt.length);
  for (let i = 0; i < n; i += 1) {
    const x = at[i] ?? "";
    const y = bt[i] ?? "";
    if (x < y) return -1;
    if (x > y) return 1;
  }
  return 0;
});

function getPath(document: unknown, pointer: string): unknown {
  if (pointer === "") return document;
  let current = document;
  for (const raw of pointer.slice(1).split("/")) {
    const token = raw.replace(/~1/g, "/").replace(/~0/g, "~");
    if (current !== null && typeof current === "object" && !Array.isArray(current)) {
      const record = current as Record<string, unknown>;
      if (!(token in record)) throw new Error("SOURCE_PATH_NOT_FOUND: " + pointer);
      current = record[token];
    } else if (Array.isArray(current)) {
      if (!/^\d+$/.test(token) || Number(token) >= current.length) {
        throw new Error("SOURCE_PATH_NOT_FOUND: " + pointer);
      }
      current = current[Number(token)];
    } else {
      throw new Error("SOURCE_PATH_NOT_FOUND: " + pointer);
    }
  }
  return current;
}

function canonical(value: unknown): string {
  if (Array.isArray(value)) {
    return "[" + value.map(canonical).join(",") + "]";
  }
  if (value !== null && typeof value === "object") {
    const record = value as Record<string, unknown>;
    return "{" + Object.keys(record).sort().map((key) => JSON.stringify(key) + ":" + canonical(record[key])).join(",") + "}";
  }
  if (typeof value === "number" && !Number.isFinite(value)) {
    throw new Error("INVALID_JSON: non-finite number");
  }
  return JSON.stringify(value);
}

function semanticEqual(left: unknown, right: unknown): boolean {
  if (typeof left === "boolean" || typeof right === "boolean") return typeof left === "boolean" && typeof right === "boolean" && left === right;
  if (typeof left === "number" || typeof right === "number") {
    if (typeof left !== "number" || typeof right !== "number") return false;
    if (!Number.isFinite(left) || !Number.isFinite(right)) throw new Error("NUMERIC_PRECISION_RISK: non-finite number");
    if ((Number.isInteger(left) && !Number.isSafeInteger(left)) || (Number.isInteger(right) && !Number.isSafeInteger(right))) throw new Error("NUMERIC_PRECISION_RISK: unsafe integer");
    return left === right;
  }
  if (Array.isArray(left) || Array.isArray(right)) return Array.isArray(left) && Array.isArray(right) && left.length === right.length && left.every((item, index) => semanticEqual(item, right[index]));
  if ((left !== null && typeof left === "object") || (right !== null && typeof right === "object")) {
    if (left === null || right === null || typeof left !== "object" || typeof right !== "object" || Array.isArray(left) || Array.isArray(right)) return false;
    const leftRecord = left as Record<string, unknown>;
    const rightRecord = right as Record<string, unknown>;
    const keys = Object.keys(leftRecord);
    return keys.length === Object.keys(rightRecord).length && keys.every((key) => Object.hasOwn(rightRecord, key) && semanticEqual(leftRecord[key], rightRecord[key]));
  }
  return left === right;
}

function countNodes(value: unknown): number {
  if (Array.isArray(value)) return 1 + value.reduce<number>((total, item) => total + countNodes(item), 0);
  if (value !== null && typeof value === "object") {
    return 1 + Object.values(value as Record<string, unknown>).reduce<number>((total, item) => total + countNodes(item), 0);
  }
  return 1;
}

function checkLimits(value: unknown): void {
  if (countNodes(value) > MAX_OUTPUT_NODES) throw new Error("EVALUATION_LIMIT_EXCEEDED: max_output_nodes");
  let total = 0;
  function visit(item: unknown): void {
    if (typeof item === "string") {
      total += item.length;
      if (total > MAX_STRING_LENGTH) throw new Error("EVALUATION_LIMIT_EXCEEDED: max_string_length");
    } else if (Array.isArray(item)) {
      for (const child of item) visit(child);
    } else if (item !== null && typeof item === "object") {
      for (const child of Object.values(item as Record<string, unknown>)) visit(child);
    }
  }
  visit(value);
}

function numeric(value: unknown): number {
  if (typeof value !== "number") {
    throw new Error("TYPE_MISMATCH: numeric operation requires a number");
  }
  if (!Number.isFinite(value)) throw new Error("NUMERIC_PRECISION_RISK: non-finite number");
  if (Number.isInteger(value) && Math.abs(value) > MAX_SAFE_INTEGER) {
    throw new Error("NUMERIC_PRECISION_RISK: unsafe integer");
  }
  return value;
}

function normalizeNumber(value: number): number {
  if (!Number.isFinite(value)) throw new Error("NUMERIC_PRECISION_RISK: non-finite result");
  if (Number.isInteger(value) && Math.abs(value) <= MAX_SAFE_INTEGER) return Math.trunc(value);
  if (Math.abs(value) > MAX_SAFE_INTEGER) throw new Error("NUMERIC_PRECISION_RISK: unsafe integer result");
  return value;
}

function roundHalf(value: number, digits: number): number {
  const factor = Math.pow(10, digits);
  const scaled = Math.round(Math.abs(value) * factor + Number.EPSILON) / factor;
  return normalizeNumber((value === 0 ? 0 : Math.sign(value)) * scaled);
}

function cast(value: unknown, targetType: string): unknown {
  if (targetType === "string") {
    if (value === null) return "null";
    if (typeof value === "boolean") return value ? "true" : "false";
    if (typeof value === "number" && Number.isInteger(value)) return String(Math.trunc(value));
    if (typeof value === "string" || typeof value === "number") return String(value);
    throw new Error("TYPE_MISMATCH: cast to string requires scalar");
  }
  if (targetType === "boolean") {
    if (typeof value === "boolean") return value;
    if (typeof value === "string" && (value.toLowerCase() === "true" || value.toLowerCase() === "false")) {
      return value.toLowerCase() === "true";
    }
    throw new Error("TYPE_MISMATCH: cast to boolean requires boolean");
  }
  if (targetType === "integer") {
    if (typeof value === "boolean") throw new Error("TYPE_MISMATCH: cast to integer rejects booleans");
    if (typeof value === "number" && Number.isInteger(value)) {
      if (Math.abs(value) > MAX_SAFE_INTEGER) throw new Error("NUMERIC_PRECISION_RISK: unsafe integer");
      return value;
    }
    if (typeof value === "string" && INTEGER.test(value)) {
      const parsed = Number(value);
      if (!Number.isSafeInteger(parsed)) throw new Error("NUMERIC_PRECISION_RISK: unsafe integer");
      return parsed;
    }
    throw new Error("TYPE_MISMATCH: cast to integer requires integer string");
  }
  if (targetType === "number") {
    if (typeof value === "boolean") throw new Error("TYPE_MISMATCH: cast to number rejects booleans");
    if (typeof value === "string" && !DECIMAL.test(value)) throw new Error("TYPE_MISMATCH: cast to number requires finite numeric value");
    if (typeof value === "number" && !Number.isFinite(value)) throw new Error("NUMERIC_PRECISION_RISK: non-finite number");
    const parsed = typeof value === "number" || typeof value === "string" ? Number(value) : Number.NaN;
    if (!Number.isFinite(parsed)) throw new Error("TYPE_MISMATCH: cast to number requires finite numeric value");
    return normalizeNumber(parsed);
  }
  throw new Error("INVALID_EXPRESSION: unknown cast target");
}

function parseDate(value: unknown): string {
  if (typeof value !== "string") throw new Error("INVALID_DATE: parse_date requires string");
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?(Z|[+-]\d{2}:\d{2})$/.exec(value);
  if (!match) throw new Error("INVALID_DATE: invalid RFC3339");
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  if (month < 1 || month > 12 || hour > 23 || minute > 59 || second > 59) throw new Error("INVALID_DATE: invalid RFC3339 component");
  const milliseconds = Number((match[7] ?? "").slice(0, 3).padEnd(3, "0"));
  let utc = Date.UTC(year, month - 1, day, hour, minute, second, milliseconds);
  const roundTrip = new Date(Date.UTC(year, month - 1, day, hour, minute, second, milliseconds));
  if (roundTrip.getUTCFullYear() !== year || roundTrip.getUTCMonth() !== month - 1 || roundTrip.getUTCDate() !== day || roundTrip.getUTCHours() !== hour || roundTrip.getUTCMinutes() !== minute || roundTrip.getUTCSeconds() !== second) throw new Error("INVALID_DATE: invalid RFC3339 calendar date");
  const zone = match[8];
  if (zone !== "Z") {
    const offsetHours = Number(zone.slice(1, 3));
    const offsetMinutes = Number(zone.slice(4, 6));
    if (offsetHours > 23 || offsetMinutes > 59) throw new Error("INVALID_DATE: invalid RFC3339 offset");
    const sign = zone[0] === "-" ? 1 : -1;
    const offset = (offsetHours * 60 + offsetMinutes) * sign * 60000;
    utc += offset;
  }
  return new Date(utc).toISOString();
}

function formatDate(value: unknown, pattern: string): string {
  if (typeof value !== "string") throw new Error("INVALID_DATE: format_date requires string");
  const parsed = parseDate(value);
  const values: Record<(typeof DATE_TOKENS)[number], string> = { YYYY: parsed.slice(0, 4), MM: parsed.slice(5, 7), DD: parsed.slice(8, 10), hh: parsed.slice(11, 13), mm: parsed.slice(14, 16), ss: parsed.slice(17, 19), SSS: parsed.slice(20, 23), Z: "Z" };
  const output: string[] = [];
  let index = 0;
  while (index < pattern.length) {
    const token = DATE_TOKENS.find((candidate) => pattern.startsWith(candidate, index));
    if (token !== undefined) { output.push(values[token]); index += token.length; continue; }
    const character = pattern[index];
    if (character !== "T" && /[A-Za-z]/.test(character)) throw new Error("INVALID_DATE: unsupported date format token");
    output.push(character);
    index += 1;
  }
  return output.join("");
}

function childExpression(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error("INVALID_EXPRESSION: expression must be an object");
  return value as Record<string, unknown>;
}

function evaluate(expression: Record<string, unknown>, inputDocument: unknown, outputDocument: unknown, currentStack: unknown[], depth: number): unknown {
  if (depth > MAX_EXPRESSION_DEPTH) throw new Error("EVALUATION_LIMIT_EXCEEDED: max_expression_depth");
  const op = expression.op as string;
  if (op === "get") {
    const document = (expression.document as string | undefined) ?? "input";
    const path = expression.path as string;
    if (document === "input") return getPath(inputDocument, path);
    if (document === "output") return getPath(outputDocument, path);
    if (currentStack.length === 0) throw new Error("INVALID_EXPRESSION: current requires map context");
    return getPath(currentStack[currentStack.length - 1], path);
  }
  if (op === "literal") return expression.value;
  if (op === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(expression.fields as Record<string, Record<string, unknown>>)) {
      result[key] = evaluate(child, inputDocument, outputDocument, currentStack, depth + 1);
    }
    return result;
  }
  if (op === "array") {
    const items = expression.items as Record<string, unknown>[];
    if (items.length > MAX_ARRAY_ITEMS) throw new Error("EVALUATION_LIMIT_EXCEEDED: max_array_items");
    return items.map((item) => evaluate(item, inputDocument, outputDocument, currentStack, depth + 1));
  }
  if (op === "map") {
    const collection = evaluate(childExpression(expression.collection), inputDocument, outputDocument, currentStack, depth + 1);
    if (!Array.isArray(collection)) throw new Error("TYPE_MISMATCH: map requires array");
    if (collection.length > MAX_ARRAY_ITEMS) throw new Error("EVALUATION_LIMIT_EXCEEDED: max_array_items");
    return collection.map((item) => evaluate(expression.expression as Record<string, unknown>, inputDocument, outputDocument, [...currentStack, item], depth + 1));
  }
  if (op === "coalesce") {
    for (const operand of expression.operands as Record<string, unknown>[]) {
      let value: unknown;
      try {
        value = evaluate(operand, inputDocument, outputDocument, currentStack, depth + 1);
      } catch (error) {
        if (error instanceof Error && error.message.startsWith("SOURCE_PATH_NOT_FOUND")) continue;
        throw error;
      }
      if (value !== undefined && value !== null) return value;
    }
    return null;
  }
  if (op === "concat") {
    const parts: string[] = [];
    for (const operand of expression.operands as Record<string, unknown>[]) {
      const value = evaluate(operand, inputDocument, outputDocument, currentStack, depth + 1);
      if (typeof value !== "string") throw new Error("TYPE_MISMATCH: concat requires strings");
      parts.push(value);
    }
    return parts.join((expression.separator as string | undefined) ?? "");
  }
  if (op === "cast") {
    return cast(evaluate(childExpression(expression.value), inputDocument, outputDocument, currentStack, depth + 1), expression.target_type as string);
  }
  if (op === "if") {
    const condition = evaluate(childExpression(expression.condition), inputDocument, outputDocument, currentStack, depth + 1);
    if (typeof condition !== "boolean") throw new Error("TYPE_MISMATCH: if requires boolean");
    return evaluate(childExpression(condition ? expression.then : expression.otherwise), inputDocument, outputDocument, currentStack, depth + 1);
  }
  if (op === "equals") {
    const left = evaluate(childExpression(expression.left), inputDocument, outputDocument, currentStack, depth + 1);
    const right = evaluate(childExpression(expression.right), inputDocument, outputDocument, currentStack, depth + 1);
    return semanticEqual(left, right);
  }
  if (op === "not") {
    const value = evaluate(childExpression(expression.value), inputDocument, outputDocument, currentStack, depth + 1);
    if (typeof value !== "boolean") throw new Error("TYPE_MISMATCH: not requires boolean");
    return !value;
  }
  if (op === "and" || op === "or") {
    const values = (expression.operands as Record<string, unknown>[]).map((item) => evaluate(item, inputDocument, outputDocument, currentStack, depth + 1));
    if (values.some((item) => typeof item !== "boolean")) throw new Error("TYPE_MISMATCH: boolean operation requires booleans");
    return op === "and" ? values.every(Boolean) : values.some(Boolean);
  }
  if (op === "lookup") {
    const key = evaluate(childExpression(expression.key), inputDocument, outputDocument, currentStack, depth + 1);
    const values = expression.values as Record<string, unknown>;
    if (typeof key === "string" && key in values) return values[key];
    const fallback = expression.default;
    return fallback === undefined || fallback === null ? null : evaluate(fallback as Record<string, unknown>, inputDocument, outputDocument, currentStack, depth + 1);
  }
  if (op === "add" || op === "subtract" || op === "multiply" || op === "divide") {
    const left = numeric(evaluate(childExpression(expression.left), inputDocument, outputDocument, currentStack, depth + 1));
    const right = numeric(evaluate(childExpression(expression.right), inputDocument, outputDocument, currentStack, depth + 1));
    if (op === "divide" && right === 0) throw new Error("DIVIDE_BY_ZERO");
    const result = op === "add" ? left + right : op === "subtract" ? left - right : op === "multiply" ? left * right : left / right;
    return normalizeNumber(result);
  }
  if (op === "round") {
    return roundHalf(numeric(evaluate(childExpression(expression.value), inputDocument, outputDocument, currentStack, depth + 1)), Number(expression.digits ?? 0));
  }
  if (op === "parse_date") {
    return parseDate(evaluate(childExpression(expression.value), inputDocument, outputDocument, currentStack, depth + 1));
  }
  if (op === "format_date") {
    return formatDate(evaluate(childExpression(expression.value), inputDocument, outputDocument, currentStack, depth + 1), expression.pattern as string);
  }
  throw new Error("INVALID_EXPRESSION: unknown operation");
}

function assign(document: Record<string, unknown>, pointer: string, value: unknown): Record<string, unknown> {
  const tokens = pointer ? pointer.replace(/^\//, "").split("/") : [];
  const result = { ...document };
  let current = result;
  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index].replace(/~1/g, "/").replace(/~0/g, "~");
    if (/^\d+$/.test(token)) throw new Error("INVALID_INPUT: numeric target index");
    if (index === tokens.length - 1) {
      current[token] = value;
    } else {
      const existing = current[token];
      if (existing === undefined || existing === null || (typeof existing === "object" && !Array.isArray(existing))) {
        const child: Record<string, unknown> = existing !== null && typeof existing === "object" ? { ...(existing as Record<string, unknown>) } : {};
        current[token] = child;
        current = child;
      } else {
        throw new Error("OVERLAPPING_TARGET_ASSIGNMENT");
      }
    }
  }
  return result;
}

export function transform(source: unknown): unknown {
  if (source === null || typeof source !== "object" || Array.isArray(source)) {
    throw new Error("INVALID_INPUT: source must be an object");
  }
  const input = source as Record<string, unknown>;
  let output: Record<string, unknown> = {};
  for (const target of TARGETS) {
    const value = evaluate(RULES[target], input, output, [], 0);
    checkLimits(value);
    output = assign(output, target, value);
  }
  return output;
}
"""


def generate_typescript(
    mapping: MappingDocument,
    *,
    source_schema: SchemaDocument,
    target_schema: SchemaDocument,
) -> GeneratedArtifact:
    require_static_valid(mapping, source_schema=source_schema, target_schema=target_schema)
    rules = {rule.target: rule.expression.model_dump(mode="json") for rule in mapping.rules}
    source = (
        _RUNTIME.replace("__MAPPING_ID__", json.dumps(mapping.id))
        .replace("__MAPPING_SHA__", json.dumps(mapping_sha256(mapping)))
        .replace("__RULES__", json.dumps(rules, ensure_ascii=False, sort_keys=True))
    )
    return GeneratedArtifact(
        language="typescript",
        mapping_id=mapping.id,
        mapping_sha256=mapping_sha256(mapping),
        source=source,
    )
